spring:
  profiles:
    active: local

  application:
    name: backend

server:
  port: 8080

firebase:
  service-account-path: ${FIREBASE_CREDENTIALS_PATH}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: focustrain-backend
